fragment MediaPage on Media {
  id
  idMal
  title {
    userPreferred
    romaji
    english
    native
  }
  description
  coverImage {
    large
    extraLarge
  }
  bannerImage
  format
  duration
  status
  startDate {
    year
    month
    day
  }
  endDate {
    year
    month
    day
  }
  season
  seasonYear
  isAdult
  popularity
  averageScore
  genres
  tags {
    name
  }
}
